env:
  global:
  - REPO_DIR=checkout
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
  - secure: rCbM0yph0EQmyVI1zMWjIRQ4Fgx2UQtyop6nmn+BiWalRy3wbuXIiUrAD8z6Ev/OLDYp2iaNuDy2YQ38MQyrjAQxnGBBSwwx0CSt/GGLCeqtDwlLPsO2uTC0ZxO9cc3+A1UP2SrEQRdEne1lfBvL5+gwcjvtXfPAXnXkuMpVKRMTaKj9iVmssmt79zu11EWlAN+9qS6nZ4gekkRNSL6KeLOcQchRBoLf1Gb4MhyWTsSTgUyYM/NrBhcNFVIV5Dc25RjoIFlMyLZO9VN3Yli+OHDTEOr1U8gzDsX+7V4dvCM+5XayytcfGWnhzSXLTOKhzxfWEl4R2V4ma+VQjWmVhQMKuQEsnPsBCDBLr7Nrt36sFz7ZjhqomwzrbwLJ+lyj4Wez28cLdAvW+fNcw3CWFgrgz+NNu5rLwXyRiP7vxlyrSuz0ZSPT8LtP3V0zmKtTK3KCy7IaNwvH/kkCKncUu4ll6gOMvWpFxlL9WlLJ71uw9g2JNwFWW6caPQKeJ0fmDyfMbTnwyG0bq2cI+TStrQUx4Bayn8PW29nmevA9PkQKcjoDGaVHUDmpwdr0Mrs5MiFJ8SNIcWzLz5iUYP76AAI47Q6/xH2pwexrXU5hmMPgc6scZIL3dAHTLtZh6iznbyBtGQNR4bREfP/0j2PKuQ3cOfuztlqv2bmAiiwvFK4=
language: python
sudo: required
dist: xenial
services: docker
if: type = push AND tag IS blank AND branch =~ /^branch-for-/
matrix:
  include:
  - os: linux
    env: MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - UNICODE_WIDTH=16
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=2.7
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.5
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.7
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gettext; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force gettext; fi
- pip install -Ur ./requirements.txt
- eval $(python ./run.py build-spec build-spec.json)
- git clone "${BUILD_SPEC_CLONE_URL}" "$REPO_DIR"
- export BUILD_COMMIT="${BUILD_SPEC_COMMIT}"
- export PACKAGE_NAME="${BUILD_SPEC_PACKAGE_NAME}"
- cat config.sh.template | envsubst > config.sh
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
after_success:
- pip install -Ur ./requirements.txt
- python ./run.py upload --build-spec build-spec.json ${TRAVIS_BUILD_DIR}/wheelhouse
